# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f0fc29d3ea4c1ad58077a23be92ff093227e997ed985fd2a33fe8d454ef31d9bc1b904d31f7eff3f5413626108e317e80302fc459f986828e24891bf6f3214b

test:
  secret_key_base: 65eead909e16880c525cad30d0138119890deebac1a77d8767a3c8a2d1ec3574c2245427fe556c2dc3ba658352fa7ffc60bc27e9ad21cd663dadcb3d5538b802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
