# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 082ea91215281d14287654fb934a63a52f2f5d570389f9bff68cc4029a5bdb0379f716b0dd777171a864ce9bf9ec187438423436351e3eedf70f424895ce66f0

test:
  secret_key_base: ffc6b3878312c7ab2d293d7aae2f9999f9c174b914c5488d69f56318e183def342c2fa39d23bccce7b50dc29496547ef3edef0909dd49b45f59876f486e54cfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
