# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 131beca744195e98c2b34622bb7773fb2215fbe0681e4c1c0de3bddb86974fccfd65e642772fa18b958c9b14ac5c2d3f6cb83fa0da4ceb7321ad81ebc6d72a24

test:
  secret_key_base: 5d38edbf3178e2183b679d384e3f95f9e6270fdb5fa051fb8d859a4a46c987b809ff493e3cd9e433fe0c8f723976870629cd8ae0e218219aa0f571bdf4394741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
